### ISSUE TITLE
Link pop-up hidden behind block toolbar

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/gutenberg-everywhere#133]
In WP.org forums, after publishing a comment on a review, I went back to edit a link, but was initially unable to do so, since the formatting toolbar overlaps the link pop-up. 

Could we perhaps make the z-index on the link pop-up higher than the formatting toolbar? I eventually managed to work around the glitch by scrolling the window up and down a bit, and the overlap finally went away.

<img width="799" alt="link-pop-up" src="https://user-images.githubusercontent.com/7662449/211847799-c27c4711-3d0f-4e33-b686-1a68486891d4.png">

Moved from https://meta.trac.wordpress.org/ticket/6608#comment:67 at Dion's request

**Comment by johngodley** [comment]
Could you add a link to a post where this happens? I can't quite reproduce it in the same way as shown here.

**Comment by kathrynwp** [comment]
@johngodley sure, it was here. Thanks!

https://wordpress.org/support/topic/getting-worse-with-every-update-2/

**Comment by johngodley** [comment]
How did you get the popup to appear over the toolbar? No matter what I do the popup is always below the toolbar. Is this in a particular browser? Can you maybe include a full window screenshot for context?

**Comment by johngodley** [comment]
I've released 1.14.1 which changes the z-index of the bottom toolbar. I don't know how you've got a popover to appear over the top toolbar, but for wp.org there seems to be a specific style that sets the z-index of that one, and it might need changing there too:

```css
/* Move the Block Editor toolbar below the Header & Also Viewing z-index bar */
.iso-editor.has-fixed-toolbar .interface-interface-skeleton__header {
	z-index: 100;
}
```
